### ISSUE TITLE
Load Error when trying to open file on the supported file list

### ISSUE THREAD

**Issue by Skiisad** [Synthlight/RE-Editor#11]
Whenever I try to open the DogFreeUseParam.user.2 file, which is on the SUPPORTED_FILES list, I receive the following error:

---
Load Error

Error occurred. Press Ctrl+C to copy the contents of this window and report to the developer.

Target File: C:\~~~\natives\STM\otomo\OtDog\UserData\DogFreeUseParam.user.2

System.IO.EndOfStreamException: Unable to read beyond the end of the stream.

   at System.IO.BinaryReader.InternalRead(Int32 numBytes)

   at System.IO.BinaryReader.ReadInt32()

   at RE_Editor.Common.Models.RszObject.Read(BinaryReader reader, UInt32 hash, RSZ rsz, Int32 userDataRef) in R:\Code\RE-Editor\Common\Models\RszObject.cs:line 159

   at RE_Editor.Common.Models.RSZ.Read(BinaryReader reader, Boolean justReadHashes) in R:\Code\RE-Editor\Common\Models\RSZ.cs:line 67

   at RE_Editor.Common.Models.ReDataFile.Read(String targetFile, Boolean justReadHashes) in R:\Code\RE-Editor\Common\Models\ReDataFile.cs:line 40

   at RE_Editor.Windows.MainWindow.Load(String filePath) in R:\Code\RE-Editor\RE-Editor\Windows\MainWindow.xaml.cs:line 178

---

I've also tested out some previous versions of the editor, and they also had this issue. Not sure if it's an issue with the editor, or if I just messed something up on my end.

**Comment by Synthlight** [comment]
![image](https://github.com/user-attachments/assets/a2faa5a3-3abc-4544-bf4f-27c622192324)

![image](https://github.com/user-attachments/assets/182c6559-101d-4e52-916a-a411dc52d866)

**Comment by Skiisad** [comment]
Ah, yep, that worked, I'm just stupid. Thanks for the clarification lmao
